import type { Metadata } from "next";
import { Handshake, Headphones, Mail, MessageSquareText } from "lucide-react";
import PublicPage from "@/components/public/PublicPage";
import PageHero from "@/components/public/PageHero";
import ContactForm from "@/components/public/ContactForm";

export const metadata: Metadata = { title: "Contact | AI Article Publisher", description: "Talk to the AI Article Publisher team about plans, WordPress setup, billing, partnerships, or technical support." };
const cards = [[Mail, "Sales", "Plans, volume, and agency requirements.", "sales@aiarticlepublisher.com"], [Headphones, "Support", "Product setup and technical questions.", "support@aiarticlepublisher.com"], [Handshake, "Partnership", "Integrations and channel opportunities.", "partners@aiarticlepublisher.com"]] as const;
export default function ContactPage(){return <PublicPage><PageHero eyebrow="Contact" title="Let’s talk about your publishing workflow" description="Tell us what you publish, how your team works, and where the current process slows you down." /><section className="py-16 sm:py-20"><div className="mx-auto grid max-w-7xl gap-7 px-4 sm:px-6 lg:grid-cols-[1.25fr_0.75fr] lg:px-8"><ContactForm /><aside className="space-y-4">{cards.map(([Icon,title,copy,email])=><div key={title} className="rounded-2xl border border-slate-200 bg-white p-5"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-blue-700"><Icon className="h-4 w-4" /></span><h2 className="mt-4 text-sm font-semibold text-slate-950">{title}</h2><p className="mt-2 text-xs leading-6 text-slate-600">{copy}</p><a href={`mailto:${email}`} className="mt-3 block text-xs font-semibold text-blue-700">{email}</a></div>)}</aside></div></section><section className="border-y border-slate-200 bg-slate-50"><div className="mx-auto grid max-w-7xl gap-5 px-4 py-10 sm:px-6 md:grid-cols-3 lg:px-8">{[["How quickly will you reply?", "Most inquiries receive a response within two business days."], ["Can you help connect WordPress?", "Yes. Select WordPress setup so the right context reaches our team."], ["Do you support agencies?", "Yes. We can discuss multi-site workflows, volume, and rollout needs."]].map(([q,a])=><div key={q} className="flex gap-3"><MessageSquareText className="mt-0.5 h-4 w-4 shrink-0 text-blue-700" /><div><h3 className="text-xs font-semibold text-slate-950">{q}</h3><p className="mt-2 text-xs leading-6 text-slate-600">{a}</p></div></div>)}</div></section></PublicPage>}
