"use client";
import Link from "next/link";
import { useState, type FormEvent } from "react";
import { CheckCircle2, Loader2 } from "lucide-react";
import AuthShell from "@/components/auth/AuthShell";
import AuthCard from "@/components/auth/AuthCard";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

export default function ForgotPasswordPage(){const[email,setEmail]=useState("");const[code,setCode]=useState("");const[password,setPassword]=useState("");const[phase,setPhase]=useState<"request"|"reset"|"done">("request");const[loading,setLoading]=useState(false);const[error,setError]=useState("");const request=async(e:FormEvent)=>{e.preventDefault();setLoading(true);setError("");try{const r=await fetch("/api/auth/forgot-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email})});const d=await r.json();if(!r.ok)throw new Error(d.error);setPhase("reset");}catch(e){setError(e instanceof Error?e.message:"Request failed.");}finally{setLoading(false)}};const reset=async(e:FormEvent)=>{e.preventDefault();setLoading(true);setError("");try{const r=await fetch("/api/auth/reset-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,code,password})});const d=await r.json();if(!r.ok)throw new Error(d.error);setPhase("done");}catch(e){setError(e instanceof Error?e.message:"Reset failed.");}finally{setLoading(false)}};if(phase==="done")return <AuthShell><AuthCard title="Password updated" description="Your new password is ready to use."><div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6 text-center"><CheckCircle2 className="mx-auto h-8 w-8 text-emerald-600"/><Link href="/login" className="mt-5 inline-flex rounded-xl bg-blue-600 px-5 py-3 text-xs font-semibold text-white">Return to login</Link></div></AuthCard></AuthShell>;return <AuthShell><AuthCard title={phase==="request"?"Reset your password":"Enter your reset code"} description={phase==="request"?"We’ll email a secure 6-digit code if the account exists.":`Enter the code sent to ${email} and choose a new password.`} footer={<Link href="/login" className="font-semibold text-blue-700">Back to login</Link>}>{phase==="request"?<form onSubmit={request} className="space-y-4"><div><Label>Email address</Label><Input type="email" value={email} onChange={(e)=>setEmail(e.target.value)} placeholder="you@company.com"/></div>{error?<p className="text-xs text-red-600">{error}</p>:null}<Button className="w-full" disabled={loading}>{loading?<Loader2 className="h-4 w-4 animate-spin"/>:null}{loading?"Sending...":"Send reset code"}</Button></form>:<form onSubmit={reset} className="space-y-4"><div><Label>Reset code</Label><Input value={code} onChange={(e)=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} placeholder="000000" className="text-center tracking-[0.35em]"/></div><div><Label>New password</Label><Input type="password" value={password} onChange={(e)=>setPassword(e.target.value)} placeholder="Minimum 8 characters"/></div>{error?<p className="text-xs text-red-600">{error}</p>:null}<Button className="w-full" disabled={loading}>{loading?<Loader2 className="h-4 w-4 animate-spin"/>:null}{loading?"Updating...":"Update password"}</Button></form>}</AuthCard></AuthShell>}
