"use client";

import Link from "next/link";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Eye, EyeOff, Loader2 } from "lucide-react";
import AuthShell from "@/components/auth/AuthShell";
import AuthCard from "@/components/auth/AuthCard";
import GoogleAuthButton from "@/components/auth/GoogleAuthButton";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

export default function RegisterPage(){
 const router=useRouter(); const[name,setName]=useState("");const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[confirm,setConfirm]=useState("");const[terms,setTerms]=useState(false);const[show,setShow]=useState(false);const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[verify,setVerify]=useState(false);const[code,setCode]=useState("");
 const register=async(e:FormEvent)=>{e.preventDefault();setError("");if(name.trim().length<2)return setError("Enter your full name.");if(password.length<8)return setError("Use at least 8 characters for your password.");if(password!==confirm)return setError("Passwords do not match.");if(!terms)return setError("Accept the Terms and Privacy Policy to continue.");setLoading(true);try{const res=await fetch("/api/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,email,password})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Registration failed.");setVerify(true);}catch(e){setError(e instanceof Error?e.message:"Registration failed.");}finally{setLoading(false)}};
 const complete=async(e:FormEvent)=>{e.preventDefault();setLoading(true);setError("");try{const res=await fetch("/api/auth/verify-email",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,code})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Verification failed.");router.push("/login");}catch(e){setError(e instanceof Error?e.message:"Verification failed.");}finally{setLoading(false)}};
 if(verify)return <AuthShell><AuthCard title="Verify your email" description={`Enter the 6-digit code sent to ${email}.`} footer={<button className="font-semibold text-blue-700" onClick={()=>setVerify(false)}>Change account details</button>}><form onSubmit={complete} className="space-y-4"><div><Label>Verification code</Label><Input value={code} onChange={(e)=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} inputMode="numeric" placeholder="000000" className="text-center tracking-[0.35em]"/></div>{error?<p className="rounded-xl border border-red-200 bg-red-50 px-3 py-2 text-xs text-red-700">{error}</p>:null}<Button className="w-full" disabled={loading||code.length!==6}>{loading?<Loader2 className="h-4 w-4 animate-spin"/>:null}{loading?"Verifying...":"Verify account"}</Button></form></AuthCard></AuthShell>;
 return <AuthShell><AuthCard title="Create your account" description="Start building a faster, more consistent WordPress publishing workflow." footer={<>Already have an account? <Link href="/login" className="font-semibold text-blue-700">Sign in</Link></>}><GoogleAuthButton/><div className="my-5 flex items-center gap-3"><span className="h-px flex-1 bg-slate-200"/><span className="text-[10px] uppercase tracking-wider text-slate-400">or continue with email</span><span className="h-px flex-1 bg-slate-200"/></div><form onSubmit={register} className="space-y-3"><div><Label>Full name</Label><Input value={name} onChange={(e)=>setName(e.target.value)} placeholder="Your full name" autoComplete="name"/></div><div><Label>Email address</Label><Input type="email" value={email} onChange={(e)=>setEmail(e.target.value)} placeholder="you@company.com" autoComplete="email"/></div><div><Label>Password</Label><div className="relative"><Input type={show?"text":"password"} className="pr-9" value={password} onChange={(e)=>setPassword(e.target.value)} placeholder="Minimum 8 characters" autoComplete="new-password"/><button type="button" className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400" onClick={()=>setShow(!show)}>{show?<EyeOff className="h-4 w-4"/>:<Eye className="h-4 w-4"/>}</button></div></div><div><Label>Confirm password</Label><Input type={show?"text":"password"} value={confirm} onChange={(e)=>setConfirm(e.target.value)} placeholder="Repeat password" autoComplete="new-password"/></div><label className="flex items-start gap-2 text-[11px] leading-5 text-slate-600"><input type="checkbox" checked={terms} onChange={(e)=>setTerms(e.target.checked)} className="mt-1 rounded border-slate-300"/><span>I agree to the <Link href="/terms" className="font-semibold text-blue-700">Terms</Link> and <Link href="/privacy" className="font-semibold text-blue-700">Privacy Policy</Link>.</span></label>{error?<p className="rounded-xl border border-red-200 bg-red-50 px-3 py-2 text-xs text-red-700">{error}</p>:null}<Button className="w-full" disabled={loading}>{loading?<Loader2 className="h-4 w-4 animate-spin"/>:null}{loading?"Creating account...":"Create account"}</Button></form></AuthCard></AuthShell>
}
