import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, CloudUpload, FileText, ImageIcon, Newspaper, SearchCheck, WandSparkles } from "lucide-react";
import PublicPage from "@/components/public/PublicPage";
import PageHero from "@/components/public/PageHero";

export const metadata: Metadata = { title: "Features | AI Article Publisher", description: "Explore AI writing, WordPress publishing, Google Doc import, News Autopilot, image generation, and SEO metadata." };

const features = [
  [WandSparkles, "AI Article Generator", "Generate structured, WordPress-ready HTML from a title, brief, keywords, focus keyword, tone, required links, and target length.", ["300 to 5,000 words", "Required-link validation", "Editable HTML preview"]],
  [CloudUpload, "WordPress Publishing", "Connect multiple WordPress sites and deliver complete posts with taxonomy, media, excerpts, and publishing controls.", ["Draft, publish, or schedule", "Categories and tags", "Multi-site targets"]],
  [FileText, "Google Doc Import", "Bring editorial work into WordPress without rebuilding document structure or manually uploading every embedded image.", ["Public Doc URL or ID", "Front matter support", "Embedded image upload"]],
  [Newspaper, "News Autopilot", "Use current NewsData sources as research input for original, reviewable articles with fresh imagery and metadata.", ["Category and keyword filters", "Up to 5 items per run", "Draft-first workflow"]],
  [ImageIcon, "Image Generation", "Create a featured image and contextual visuals that are uploaded into the WordPress Media Library with useful alt text.", ["Featured image generation", "Up to 10 in-post images", "Automatic media upload"]],
  [SearchCheck, "SEO Metadata", "Prepare the search and social fields needed for consistent publishing across supported WordPress SEO plugins.", ["AIOSEO and Yoast", "Canonical and focus keyword", "Open Graph and X fields"]],
] as const;

export default function FeaturesPage() {
  return <PublicPage><PageHero eyebrow="Product features" title="A complete production line for WordPress content" description="Plan, generate, optimize, review, and publish without handing work between disconnected tools."><Link href="/register" className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-xs font-semibold text-white">Start Free <ArrowRight className="h-3.5 w-3.5" /></Link></PageHero><section className="py-20"><div className="mx-auto max-w-7xl space-y-8 px-4 sm:px-6 lg:px-8">{features.map(([Icon, title, description, points], index) => <article key={title} className="grid items-center gap-8 rounded-[28px] border border-slate-200 bg-white p-6 sm:p-8 lg:grid-cols-2"><div className={index % 2 ? "lg:order-2" : ""}><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-50 text-blue-700"><Icon className="h-5 w-5" /></span><h2 className="mt-5 text-2xl font-semibold tracking-[-0.04em] text-slate-950">{title}</h2><p className="mt-4 max-w-xl text-sm leading-7 text-slate-600">{description}</p><ul className="mt-5 grid gap-2">{points.map((point) => <li key={point} className="flex items-center gap-2 text-xs text-slate-700"><span className="h-1.5 w-1.5 rounded-full bg-blue-600" />{point}</li>)}</ul></div><div className={index % 2 ? "lg:order-1" : ""}><div className="rounded-2xl border border-slate-200 bg-slate-50 p-4 shadow-inner"><div className="flex items-center justify-between border-b border-slate-200 pb-3"><span className="text-[10px] font-bold uppercase tracking-wider text-slate-500">{title} workspace</span><span className="rounded-full bg-emerald-50 px-2 py-1 text-[9px] font-semibold text-emerald-700">Ready</span></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="h-20 rounded-xl bg-white shadow-sm" /><div className="h-20 rounded-xl bg-white shadow-sm" /><div className="h-20 rounded-xl bg-blue-600/10" /></div><div className="mt-3 h-32 rounded-xl border border-slate-200 bg-white p-4"><div className="h-2 w-2/3 rounded bg-slate-300" /><div className="mt-4 h-2 rounded bg-slate-200" /><div className="mt-2 h-2 w-5/6 rounded bg-slate-200" /><div className="mt-2 h-2 w-3/4 rounded bg-slate-200" /></div></div></div></article>)}</div></section></PublicPage>;
}
